### ISSUE TITLE
cannot convert arg0358cf663 (type []Window) to type unsafe.Pointer

### ISSUE THREAD

**Issue by F0rth** [golang-ui/glfw#2]
Hi,

I can't go build glfw, here are errors I got:
# github.com/golang-ui/glfw
./cgo_helpers.go:373: cannot convert arg0358cf663 (type []Window) to type unsafe.Pointer
./cgo_helpers.go:412: cannot convert arg0e3c4fd6a (type []Window) to type unsafe.Pointer
./cgo_helpers.go:451: cannot convert arg0e25779b2 (type []Window) to type unsafe.Pointer
./cgo_helpers.go:488: cannot convert arg09f26befc (type []Window) to type unsafe.Pointer
./cgo_helpers.go:525: cannot convert arg016af50d3 (type []Window) to type unsafe.Pointer
./cgo_helpers.go:563: cannot convert arg0bb24b88b (type []Window) to type unsafe.Pointer
./cgo_helpers.go:601: cannot convert arg0ae059393 (type []Window) to type unsafe.Pointer
./cgo_helpers.go:640: cannot convert arg08e0aa0a (type []Window) to type unsafe.Pointer
./cgo_helpers.go:680: cannot convert arg039751795 (type []Window) to type unsafe.Pointer
./cgo_helpers.go:719: cannot convert arg06d33066c (type []Window) to type unsafe.Pointer
./cgo_helpers.go:719: too many errors

**Comment by xlab** [comment]
1) Consider updating to the latest cgogen
```
$ go get -u github.com/xlab/cgogen
```

2) If not helping, you'd better fallback to http://github.com/go-gl/glfw
